### ISSUE TITLE
[feature] Custom snippet

### ISSUE THREAD

**Issue by ghost** [mfbx9da4/coderacer#1]
I would like to be able to practice touch typing with some text that I introduce, or I'd give a link to a raw github page and load that text.

**Comment by mfbx9da4** [comment]
Why do you want to do that? Is it because there's something specific you want to practice or because you don't like the generated snippets at the moment?

**Comment by ghost** [comment]
The generated snippets are perfect.

I'd want to select a custom snippet because I may catch on to some things about a project that interests me while practicing.

**Comment by ghost** [comment]
Actually I've thought better about it and it doesn't make sense if this is for competing with other people to use your custom snippets.
