### ISSUE TITLE
Not deteclting backtick on windows

### ISSUE THREAD

**Issue by paoloricciuti** [mfbx9da4/coderacer#3]
I've tryed playing but got stuck on a backtick despite writing the good character combination to get the backtick in Windows.

I would have tryed to reproduce but i can't choose a specific fragment of code and not every piece of code has the backtick.

The issue is definitely here: https://github.com/mfbx9da4/coderacer/blob/72d7b1d1e78411fd82046e6a248c73e3dbd9b7b3/sveltekit/src/routes/race.svelte#L162-L187

Handling the keydown event has it's own set of problems. The best solution would be to let the user write in an input (handled by the browser) and use the input event to check for the correctness.

If you want i might try to take a shot at this and open a PR. Let me know.

**Comment by mfbx9da4** [comment]
A PR would be awesome thanks for finding!

**Comment by paoloricciuti** [comment]
I'll try to throw something together as soon as i can. This would in theory allow also for mobile usage if that's what you are after.

**Comment by mfbx9da4** [comment]
It would need a redesign for mobile and I don't think people touch type on mobile so don't think mobile support is necessary
