### ISSUE TITLE
Websocket server crashing

### ISSUE THREAD

**Issue by paoloricciuti** [mfbx9da4/coderacer#5]
I was looking at the code of the websocket server because as mentioned in #4 i was experiencing crashes in a particular situation (i was closing the browser after the new race was created)

looking at the code here

https://github.com/mfbx9da4/coderacer/blob/72d7b1d1e78411fd82046e6a248c73e3dbd9b7b3/deno/src/utils/BroadcastMethods.ts#L39-L44

if the actual error is on

https://github.com/mfbx9da4/coderacer/blob/72d7b1d1e78411fd82046e6a248c73e3dbd9b7b3/deno/src/utils/BroadcastMethods.ts#L41

it will also fail on line

https://github.com/mfbx9da4/coderacer/blob/72d7b1d1e78411fd82046e6a248c73e3dbd9b7b3/deno/src/utils/BroadcastMethods.ts#L43

it should be a quite simple fix surrounding the second post message with a try catch too (this should at least prevent the server from crashing).

I think deno it's probably restarting every times it crashes and this would prevent this behavior.

If you want i can add a this in #4

**Comment by paoloricciuti** [comment]
Nervermind...it was a simple enaugh change that i did it in #4 , i checked and it should not crash anymore. Let me know if you want me to revert that change.

**Comment by mfbx9da4** [comment]
Nice job! 👀  At first glance, seems like a good fix.
